// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRxUjw_ciw2Nzf7A87FeSihVT39CWEsI',
    appId: '1:63204438281:web:271f0096eceac3aa5e63d8',
    messagingSenderId: '63204438281',
    projectId: 'message-app-607fe',
    authDomain: 'message-app-607fe.firebaseapp.com',
    storageBucket: 'message-app-607fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4qux12jHqi3eoq1vAJyTRF27_sw8gr_o',
    appId: '1:63204438281:android:d936b5aa4e6d6b365e63d8',
    messagingSenderId: '63204438281',
    projectId: 'message-app-607fe',
    storageBucket: 'message-app-607fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTnsQMgsrW47YgA0I88pxwN2vETV64VxA',
    appId: '1:63204438281:ios:9b1851f8763acaf05e63d8',
    messagingSenderId: '63204438281',
    projectId: 'message-app-607fe',
    storageBucket: 'message-app-607fe.appspot.com',
    iosClientId: '63204438281-8n3mrlocleb2s0b2q4bkikpnpo700h50.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTnsQMgsrW47YgA0I88pxwN2vETV64VxA',
    appId: '1:63204438281:ios:a7e3fb78e06330175e63d8',
    messagingSenderId: '63204438281',
    projectId: 'message-app-607fe',
    storageBucket: 'message-app-607fe.appspot.com',
    iosClientId: '63204438281-35c5q36a9mfu0knfav96qic4guag9jh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp.RunnerTests',
  );
}
